### ISSUE TITLE
Cache seems to be out of date

### ISSUE THREAD

**Issue by rotdrop** [NabuCasa/coronavirus#13]
The last values are from 

```
$ date -d '@1613377497.000'
Mo 15. Feb 09:24:57 CET 2021
```

The sources at 

https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/2/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=

seem to be up to date.

**Comment by frenck** [comment]
Somehow the job got disabled by GitHub. I've re-enabled it and generated a fresh instance. Thanks for reporting! 👍

**Comment by rotdrop** [comment]
I think this has happened again. Thx.
