### ISSUE TITLE
Is it okay to use the home-assistant.io source in other OSS projects?

### ISSUE THREAD

**Issue by strayer** [NabuCasa/coronavirus#3]
I'm thinking about integrating something like this in other projects or use it in my Grafana instance, but don't want to use the [home-assistant.io source](https://coronacache.home-assistant.io/corona.json) without permission.

Is it okay to use it in other OSS software and/or for personal use?

**Comment by mrand** [comment]
https://github.com/NabuCasa/coronavirus/blob/master/LICENSE.md
