### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Actpohomoc** [NabuCasa/coronavirus#4]

**Comment by olehs0** [comment]
Agree, It's a good question. Please provide any documentation.

**Comment by Anatolii1108** [comment]
How to use it?

**Comment by shankarpandala** [comment]
Some basic information will be helpful. At least someone else will prepare the documentation

**Comment by frenck** [comment]
There is one function...

`get_cases`, import the package and call that function, pass in an aiohttp session and it will return data.

<https://github.com/NabuCasa/coronavirus/blob/a4ad601a016354be8da127d03321a75155fcaef9/coronavirus/__init__.py#L74>

There really isn't more to it.

**Comment by jdmogollonp** [comment]
Is not clear how to use the get_cases function? Can you provide and example?

**Comment by frenck** [comment]
Sorry, I don't want to be rude; but what part is unclear?
The function requires only a single parameter, which is an aiohttp client session...

**Comment by oskrgab** [comment]
When I create the session, and used it as argument I got this:

from coronavirus import get_cases
import aiohttp

session = aiohttp.ClientSession()
print(get_cases(session))

---------------------------------

Traceback (most recent call last):
  File "Documents/coronavirus/corona_3.py", line 4, in <module>
    session = aiohttp.ClientSession()
  File "Documents/site-packages/aiohttp/client.py", line 210, in __init__
    loop = get_running_loop(loop)
  File "Documents/site-packages/aiohttp/helpers.py", line 269, in get_running_loop
    loop = asyncio.get_event_loop()
  File "/var/containers/Bundle/Application/5DFB5E26-2341-431E-8E60-EE49EA92D03C/Pyto.app/Frameworks/Python.framework/python38.zip/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
Exception ignored in: <function ClientSession.__del__ at 0x119133a60>
Traceback (most recent call last):
  File "Documents/site-packages/aiohttp/client.py", line 302, in __del__
    if not self.closed:
  File "Documents/site-packages/aiohttp/client.py", line 916, in closed
    return self._connector is None or self._connector.closed
AttributeError: 'ClientSession' object has no attribute '_connector'

**Comment by frenck** [comment]
This is all async @oskrgab... Your example is sync...

**Comment by frenck** [comment]
Untested example code, dry-coded straight in this GitHub comment box:

```py
import asyncio
import aiohttp

from coronavirus import get_cases


async def main():
	session = aiohttp.ClientSession()
    cases = await get_cases(session)

    for case in cases:
      print(f"Cases in {case.country}: {case.confirmed}")

    await session.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by jdmogollonp** [comment]
> Untested example code, dry-coded straight in this GitHub comment box:
> 
> ```python
> import asyncio
> import aiohttp
> 
> from coronavirus import get_cases
> 
> 
> async def main():
> 	session = aiohttp.ClientSession()
>     cases = await get_cases(session)
> 
>     for case in cases:
>       print(f"Cases in {case.country}: {case.confirmed}")
> 
>     await session.close()
> 
> if __name__ == "__main__":
>     loop = asyncio.get_event_loop()
>     loop.run_until_complete(main())
> ```
It would be nice to find that code at the  READ.ME. 
There are thousand researches trying to find this kind of data. And there is no time to explore the source code to figure out how to handle the session and the functions.
Thanks anyway.

**Comment by griffi-gh** [comment]
covid 
(pip install covid)
 is sipler and better
