### ISSUE TITLE
Why do we need so many parameters?

### ISSUE THREAD

**Issue by amitjslearn** [NabuCasa/coronavirus#5]
https://github.com/NabuCasa/coronavirus/blob/a4ad601a016354be8da127d03321a75155fcaef9/coronavirus/__init__.py#L16
Why do I need to pass the  `confirmed` arguments, can't we just the data by using the country name (There is no documentation provided about the usage)

**Comment by frenck** [comment]
You don't need to pass in anything to that class. That is a data class and is used to build the result of the query/returned data in:

<https://github.com/NabuCasa/coronavirus/blob/a4ad601a016354be8da127d03321a75155fcaef9/coronavirus/__init__.py#L93>

It was not meant to be used manually.

**Comment by amitjslearn** [comment]
How do I use it then?

**Comment by frenck** [comment]
Just call the `get_cases` function, it will return the processed data.

https://github.com/NabuCasa/coronavirus/blob/a4ad601a016354be8da127d03321a75155fcaef9/coronavirus/__init__.py#L74

**Comment by amitjslearn** [comment]
```
In [10]: c.get_cases(1)                                                         
Out[10]: <coroutine object get_cases at 0x7f36a8c88680>
```
Is it correct? how to see that object?

**Comment by frenck** [comment]
You cannot pass in just `1`, as the function shows, you need to pass in an aiohttp client session...

For an example implementation of this package, you could take a look at the Home Assistant project, which uses this package as part of the coronavirus integration.
